### ISSUE TITLE
How to Mirror traffic to Machine hosting mininet

### ISSUE THREAD

**Issue by scottkelso** [iwaseyusuke/docker-mininet#3]
I can't seem to figure out how to mirror traffic from within mininet to the machine hosting mininet, so that the likes of Poseidon can access it.

Currently running on Ubuntu:16.04...

- Natively: Faucet and Guage
- In Docker Containers: Mininet and Poseidon

I am spinning up a mininet with 

```
mn --topo single,3 --mac --controller=remote,ip=143.117.69.165,port=6653 --controller=remote,ip=143.117.69.165,port=6654 --switch ovsk
```

and my `faucet.yaml` is as follows

```
vlans:
    demo:
        vid: 100
        description: "demo network"
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: true
        interfaces:
            1:
                name: "h1"
                description: "host1"
                native_vlan: demo
                acl_in: mir1
            2:
                name: "h2"
                description: "host2"
                native_vlan: demo
                acl_in: mir2
            3:
                name: "m1"
                description: "mirror1"
                native_vlan: demo
                output_only: true
acls:
  mir1:
    - rule:
       actions:
         allow: 1
         mirror: 3
  mir2:
    - rule:
       actions:
         allow: 1
         mirror: 3
```

Any advice would be gratefully appreciated.
